# Cấu hình tối thiểu
title: "Tài liệu demo"
author: "Charlie"
logo: ""
only_build_toc_files: true

html:
  favicon: ""
  use_issues_button: false
  use_repository_button: false
  use_edit_page_button: false
